### ISSUE TITLE
Update ruby version

### ISSUE THREAD

**Issue by nduckwiler** [codecademy-engineering/bootstrap#49]
Currently, the bootstrap script puts [the Ruby version at 2.5.8](https://github.com/codecademy-engineering/bootstrap/blob/main/bootstrap.sh#L10). The monolith was [recently updated to 2.7.1](https://github.com/codecademy-engineering/Codecademy/pull/22658)

```
RUBY_VERSION="2.5.8"
```

Should we update the script to ruby 2.7.1 also?

**Comment by danehammer** [comment]
#50

**Comment by nduckwiler** [comment]
@danehammer I'm noticing now that [author](https://github.com/codecademy-engineering/author/blob/develop/.ruby-version) and [content_service](https://github.com/codecademy-engineering/content_service/blob/develop/.ruby-version) use 2.7.2.

Frankly, I'm not familiar with Ruby at all so I'm not sure how much this matters; I'm just providing this information in the hopes that it's useful! :)

**Comment by nduckwiler** [comment]
Resolved! We're on 2.7.5 now https://github.com/codecademy-engineering/bootstrap/pull/63
