### ISSUE TITLE
Update PATH

### ISSUE THREAD

**Issue by danehammer** [codecademy-engineering/bootstrap#51]
Not sure I understand this correctly, but it looks like we currently:
* install rbenv
* install the ruby version
* install bundler
* run `rbenv rehash`

but the user's PATH won't include `~/.rbenv/shims` so they'll still get the system ruby, e.g.:

```
ls -al `which ruby`
-r-xr-xr-x  1 root  wheel  36624 Jul  9  2020 /usr/bin/ruby
```

I think we need to append a `export PATH="$HOME/.rbenv/shims:$PATH"` to the user's path in the `install_ruby`, yeah?

**Comment by bhb603** [comment]
The bootstrap script should be adding `eval "$(rbenv init -)"` to your bashrc / zshrc, see: https://github.com/codecademy-engineering/bootstrap/blob/17c4658df040e52077d18cc586f2bcafd9b84b87/bootstrap.sh#L110

This is how rbenv updates the `$PATH` and a few other things: https://github.com/rbenv/rbenv#how-rbenv-hooks-into-your-shell

Caveats:
- you'll have to reload your shell (or re-`source` the rc file) after running `./bootstrap.sh` for this to take effect
- it only supports zsh and bash at the moment
